(function(){
  "use strict";
  var crm=window.CombinvestCRM,analysisId=crm.analysisId,customerId=crm.customerId;
  var Q_IDS=["geschlecht","alter","sport","rauchen","zivilstand","kinder","abhaengige","motorfahrzeug","haustiere","wohnen","plz","ausbildung","konfession","erwerb","brutto","kk_prio","zukunft","ziele","fixkosten"];
  var AREAS={health:"Gesundheit",pensiongap:"Vorsorge",investment:"Vermögen aufbauen","real-estate":"Immobilien","values-protection":"Versicherungen",children:"Kinder absichern","property-creation":"Lebensstandard", "tax-advantage":"Steuern optimieren"};
  var state={snapshot:{answers:{},answered:{},contracts:{},themeStatus:{}},customer:null,cloud:null,appointment:null,documents:crm.data("document-closing",{}),sealth:crm.data("sealth-check",{}),referral:crm.data("service-referral",{}),closing:crm.data("analysis-closing",{})};
  function esc(v){return String(v==null?"":v).replace(/[&<>"']/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c];});}
  function row(title,sub,value){return '<div class="row"><div><strong>'+esc(title)+'</strong>'+(sub?'<small>'+esc(sub)+'</small>':'')+'</div><span class="value">'+esc(value)+'</span></div>';}
  function setStatus(id,text,kind){var n=document.getElementById(id);n.textContent=text;n.className="status "+kind;}
  function toast(text){var n=document.getElementById("toast");n.textContent=text;n.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(function(){n.classList.remove("show");},2500);}
  function localSnapshot(){try{var raw=localStorage.getItem(crm.storageKey("analysis."+analysisId)),parsed=JSON.parse(raw||"null");if(parsed&&parsed.data)parsed=parsed.data;return parsed&&parsed.answers?parsed:null;}catch(_e){return null;}}
  function answeredCount(snapshot){return Q_IDS.filter(function(k){if(snapshot.answered&&snapshot.answered[k])return true;var v=snapshot.answers&&snapshot.answers[k];return Array.isArray(v)?v.length>0:v!==null&&v!==undefined&&v!=="";}).length;}
  function appointmentRecord(){return{date:nextDate.value,time:nextTime.value,place:nextPlace.value.trim(),purpose:nextPurpose.value.trim(),updatedAt:new Date().toISOString()};}
  function hydrateAppointment(a){if(!a)return;if(a.starts_at){var d=new Date(a.starts_at);nextDate.value=d.toISOString().slice(0,10);nextTime.value=d.toTimeString().slice(0,5);nextPlace.value=a.location||"";nextPurpose.value=a.title||"";}else{nextDate.value=a.date||"";nextTime.value=a.time||"";nextPlace.value=a.place||"";nextPurpose.value=a.purpose||"";}}
  function render(){
    var s=state.snapshot||{},answers=s.answers||{},count=answeredCount(s),profileDone=count===Q_IDS.length,hasThemeWork=Object.keys(s.themeStatus||{}).length>0,analysisReached=Number(s.step||0)>=3||hasThemeWork,contractDone=Number(s.step||0)>=2||analysisReached;
    baseRows.innerHTML=row("Profiling",count+" von "+Q_IDS.length+" Fragen beantwortet",profileDone?"Abgeschlossen":"Unvollständig")+row("Vertragscheck",Object.keys(s.contracts||{}).length+" Verträge erfasst",contractDone?"Abgeschlossen":"Offen");setStatus("baseStatus",profileDone&&contractDone?"Abgeschlossen":"Prüfen",profileDone&&contractDone?"done":"open");
    var statuses=s.themeStatus||{},keys=Object.keys(AREAS),done=keys.filter(function(k){return statuses[k]==="done";}).length,progress=keys.filter(function(k){return statuses[k]==="progress";}).length;
    themes.innerHTML=keys.map(function(k){var st=statuses[k]||"open",label=st==="done"?"Abgeschlossen":st==="progress"?"In Bearbeitung":"Offen";return '<span class="theme '+st+'">'+esc(AREAS[k])+' · '+label+'</span>';}).join("");setStatus("themeStatus",done+" erledigt",done?"done":"open");
    var open=keys.filter(function(k){return statuses[k]!=="done";});recommendations.innerHTML=open.length?open.map(function(k){return row(AREAS[k],statuses[k]==="progress"?"Bereits in Bearbeitung":"Noch nicht abgeschlossen","Weiterführen");}).join(""):row("Alle Themen bearbeitet","Keine offenen Themen aus der Risikoanalyse","Erledigt");setStatus("recommendationStatus",open.length?open.length+" offen":"Erledigt",open.length?"open":"done");
    var docs=state.documents||{},docNames=Array.isArray(docs.documents)?docs.documents:[],customerName=state.customer&&[state.customer.first_name,state.customer.last_name].filter(Boolean).join(" ").trim().toLowerCase(),documentName=[docs.firstName,docs.lastName].filter(Boolean).join(" ").trim().toLowerCase(),identityMatches=!customerName||!documentName||customerName===documentName,docReady=identityMatches&&docs.status==="ready-to-send",advisorPending=identityMatches&&docs.status==="customer-signed-advisor-pending";
    documents.innerHTML=!identityMatches?row("Dokumentdaten prüfen","Das gespeicherte Paket gehört nicht zum aktuell geöffneten Kunden","Neu erstellen"):docNames.length?docNames.map(function(n){return row(n,"PDF erstellt",docReady?"Beidseitig signiert":"Kunde signiert");}).join(""):row("Noch kein Dokumentpaket","Beratungsprotokoll und benötigte Mandate auswählen","Erstellen");if(advisorPending)documents.innerHTML+=row("Beraterunterschrift","Kundenunterschrift ist vorhanden","Ausstehend");setStatus("documentStatus",docReady?"Ready-to-send":advisorPending?"Berater offen":!identityMatches?"Daten prüfen":"Nicht erstellt",docReady?"done":advisorPending?"open":"missing");
    var selected=state.sealth&&(state.sealth.selectedPackage||state.sealth.recommendation),ref=state.referral&&state.referral.updatedAt;
    sealthRows.innerHTML=row("Sealth-Bedarfscheck",selected?String(selected).replace(/^./,function(x){return x.toUpperCase();}):"Noch nicht durchgeführt",selected?"Auswahl vorhanden":"Optional")+row("Weiterempfehlung",ref?(state.referral.firstName||"")+" "+(state.referral.lastName||""):"Noch nicht erfasst",ref?"Vorgemerkt":"Optional");setStatus("sealthStatus",selected||ref?"Erfasst":"Optional",selected||ref?"done":"open");
    var appointmentOk=!!nextDate.value;setStatus("appointmentStatus",appointmentOk?"Vorgemerkt":"Offen",appointmentOk?"done":"open");
    var readiness=[profileDone,contractDone,analysisReached,done>0,docReady||advisorPending,appointmentOk,!!selected||!!ref],readyCount=readiness.filter(Boolean).length,pct=Math.round(readyCount/readiness.length*100);progressBar.style.width=pct+"%";progressText.textContent=readyCount+" von "+readiness.length+" Abschlussbausteinen vorbereitet";
    var complete=state.closing&&state.closing.status==="completed"||(state.cloud&&state.cloud.status==="completed");if(complete){heroState.textContent="Beratung abgeschlossen";heroState.className="hero-state";finish.textContent="✓ Beratung abgeschlossen";finish.className="finish done";finish.disabled=true;finishNote.textContent=state.closing.completedAt?"Abgeschlossen am "+new Date(state.closing.completedAt).toLocaleString("de-CH"):"Verbindlich gespeichert";}else syncFinish();
  }
  function syncFinish(){var confirmations=[].slice.call(document.querySelectorAll("[data-confirm]")),all=confirmations.every(function(x){return x.checked;}),profile=answeredCount(state.snapshot)===Q_IDS.length,appointment=!!nextDate.value;finish.disabled=!(all&&profile&&appointment);finishNote.textContent=!profile?"Profiling zuerst vollständig abschliessen":!appointment?"Nächsten Termin erfassen":!all?"Alle drei Bestätigungen erforderlich":"Bereit zum verbindlichen Abschluss";}
  async function load(){
    if(!analysisId){heroCopy.textContent="Keine aktive Analyse gefunden.";return;}
    var local=localSnapshot();if(local)state.snapshot=local;
    try{if(window.CombinvestData){state.cloud=await CombinvestData.analysis(analysisId);if(state.cloud.latest_snapshot&&state.cloud.latest_snapshot.answers)state.snapshot=state.cloud.latest_snapshot;var customerData=await CombinvestData.customer(customerId);state.customer=customerData.customer;crm.save("profile",{firstName:state.customer.first_name||"",lastName:state.customer.last_name||"",birthdate:state.customer.birthdate||"",email:state.customer.email||"",phone:state.customer.phone||"",street:state.customer.street||state.customer.address_line||state.customer.address||"",zip:state.customer.postcode||"",city:state.customer.city||"",customerId:state.customer.id||customerId});var name=[state.customer.first_name,state.customer.last_name].filter(Boolean).join(" ");if(name)heroCopy.textContent="Abschlusskontrolle für "+name+": Analyse, Empfehlungen, Dokumente und nächste Schritte auf einen Blick.";}}
    catch(e){console.warn("Abschlussdaten konnten nicht vollständig aus Supabase geladen werden.",e);}
    var savedAppointment=crm.data("closing-appointment",null);hydrateAppointment(savedAppointment);
    try{if(!savedAppointment&&window.CombinvestCloud&&CombinvestCloud.client){var q=await CombinvestCloud.client.from("appointments").select("title,starts_at,location,status").eq("customer_id",customerId).gte("starts_at",new Date().toISOString()).neq("status","cancelled").order("starts_at",{ascending:true}).limit(1);if(!q.error&&q.data&&q.data[0]){state.appointment=q.data[0];hydrateAppointment(q.data[0]);}}}catch(_e){}
    render();
  }
  [nextDate,nextTime,nextPlace,nextPurpose].forEach(function(n){n.addEventListener("input",function(){render();syncFinish();});});
  document.querySelectorAll("[data-confirm]").forEach(function(n){n.addEventListener("change",syncFinish);});
  saveAppointment.addEventListener("click",function(){if(!nextDate.value){nextDate.reportValidity();nextDate.focus();return;}var record=appointmentRecord();crm.save("closing-appointment",record);state.appointment=record;render();toast("Folgetermin im Kundenabschluss vorgemerkt.");});
  printBtn.addEventListener("click",function(){window.print();});
  finish.addEventListener("click",async function(){if(this.disabled)return;var button=this,record={status:"completed",completedAt:new Date().toISOString(),appointment:appointmentRecord(),documents:state.documents||{},sealth:state.sealth||{},referral:state.referral||{}};button.disabled=true;button.textContent="Abschluss wird gespeichert …";try{if(window.CombinvestData){var cloud=await CombinvestData.analysis(analysisId),snap=cloud.latest_snapshot&&cloud.latest_snapshot.answers?cloud.latest_snapshot:state.snapshot;snap.step=3;snap.question=Q_IDS.length-1;snap.updatedAt=record.completedAt;await CombinvestData.saveAnalysis(analysisId,cloud.lock_version,3,Q_IDS.length-1,100,snap,true);}crm.save("closing-appointment",record.appointment);crm.save("analysis-closing",record);state.closing=record;state.cloud=state.cloud||{};state.cloud.status="completed";render();toast("Beratung wurde verbindlich abgeschlossen.");}catch(e){console.error(e);button.disabled=false;button.textContent="Beratung verbindlich abschliessen";finishNote.textContent="Abschluss konnte nicht gespeichert werden";toast("Speichern fehlgeschlagen. Bitte Verbindung prüfen.");}});
  load();
})();
