(function(){
  "use strict";
  function el(tag,cls,html){var n=document.createElement(tag);if(cls)n.className=cls;if(html!=null)n.innerHTML=html;return n;}
  function money(n){return "CHF "+Math.round(Number(n)||0).toLocaleString("de-CH");}
  function currentParams(path){if(window.CombinvestCRM&&CombinvestCRM.url)return CombinvestCRM.url(path);var q=new URLSearchParams(location.search);return path+(q.toString()?"?"+q.toString():"");}
  function init(){
    var input=document.querySelector(".inputs"),result=document.querySelector(".result"),form=document.querySelector(".form-grid"),source=document.getElementById("sourceFields");
    if(!input||!result||!form||!source||document.querySelector(".pk-choice"))return;
    document.querySelector(".lead").textContent="Wählen Sie das Risiko, erfassen Sie die Einkommensgrundlage und übernehmen Sie die Leistungen aus Ihren Unterlagen. Die Vorsorgelücke wird sofort verständlich sichtbar.";
    input.querySelector(".section-title").after(el("p","pension-guide-note","Die wichtigsten Angaben sind direkt sichtbar. Fachliche Annahmen und manuelle Korrekturen finden Sie unter Expertenfelder."));
    form.before(el("div","pension-subtitle","<span>1</span> Einkommen und Zielbedarf"));

    var bvgMode=document.getElementById("bvgMode"),bvgField=bvgMode.closest(".field");bvgField.classList.add("hidden");
    var pkTitle=el("div","pension-subtitle","<span>2</span> Pensionskasse erfassen");form.after(pkTitle);
    var choices=el("div","pk-choice",'<a class="pk-upload" href="'+currentParams("pk-ausweis.html")+'"><b>PK-Ausweis hochladen</b><small>Daten erfassen und kontrolliert übernehmen</small></a><button type="button" data-pk="minimum"><b>Gesetzliches Minimum</b><small>Als klar markierter Richtwert berechnen</small></button><button type="button" data-pk="statement"><b>Selbst eingeben</b><small>Werte aus Ausweis oder Verfügung</small></button>');
    pkTitle.after(choices);
    function syncChoice(){choices.querySelectorAll("[data-pk]").forEach(function(b){b.classList.toggle("active",b.dataset.pk===bvgMode.value);});}
    choices.addEventListener("click",function(e){var b=e.target.closest("[data-pk]");if(!b)return;bvgMode.value=b.dataset.pk;bvgMode.dispatchEvent(new Event("change",{bubbles:true}));syncChoice();if(b.dataset.pk==="statement")setTimeout(function(){var i=source.querySelector("input:not(:disabled)");if(i)i.focus();},40);});syncChoice();

    var sourceTitle=el("div","source-heading","<b>Leistungsbausteine</b><span>Eingaben pro Jahr</span>");source.before(sourceTitle);
    var expert=el("details","pension-expert",'<summary>Expertenfelder und Berechnungsannahmen</summary><div class="pension-expert-body"></div>'),expertBody=expert.querySelector("div");sourceTitle.before(expert);
    ["degreeField","ahvModeField","ageField","startAgeField","minimumNote","ahvCalcSummary"].forEach(function(id){var n=document.getElementById(id);if(n)expertBody.appendChild(n);});
    var quality=el("div","quality-key",'<span><b class="source-badge exact">Exakt</b> aus Unterlage / Eingabe</span><span><b class="source-badge estimate">Richtwert</b> gesetzlich berechnet oder angenähert</span>');source.after(quality);

    var children=document.getElementById("childrenField"),childBox=el("section","children-box",'<div class="pension-subtitle"><span>3</span> Kinder und Zusatzschutz</div><div class="children-slot"></div><div class="children-intro"><b>Zwei verschiedene Situationen:</b> Die IV-/BVG-Kinderrente oben ist ein Zuschlag, wenn ein Elternteil invalid wird. Für das Kind selbst besteht eine ordentliche IV-Rente frühestens ab 18 Jahren; Höhe und Anspruch hängen vom Einzelfall ab. Das Risiko wird deshalb separat und ohne erfundene gesetzliche Leistung geprüft.</div><details class="child-protection"><summary>Eigenen Schutz des Kindes prüfen</summary><div class="child-protection-body"><div class="child-grid"><div class="field"><label>Gewünschte Unterstützung / Monat</label><input id="childTarget" type="number" min="0" step="100" value="1500"></div><div class="field"><label>Bestehende private Kinderrente / Monat</label><input id="childPrivate" type="number" min="0" step="100" value="0"></div><div class="field"><label>Spar-/Anlagebetrag / Monat</label><input id="childSaving" type="number" min="0" step="25" value="0"><small>Unabhängige Vermögensbildung; ersetzt keine Einkommensabsicherung.</small></div><div class="field"><label>Sparhorizont</label><select id="childYears"><option value="10">10 Jahre</option><option value="15">15 Jahre</option><option value="18" selected>18 Jahre</option><option value="25">25 Jahre</option></select></div></div><div class="child-result"><div><small>Private Leistung</small><b id="childPrivateOut">CHF 0</b></div><div class="child-gap"><small>Ungedeckter Monatsbedarf</small><b id="childGapOut">CHF 0</b></div><div><small>Eigene Einzahlungen</small><b id="childCapitalOut">CHF 0</b></div></div></div></details>');
    quality.after(childBox);childBox.querySelector(".children-intro").innerHTML="<b>Kinderschutz separat prüfen:</b> Die Kinderrente ergänzt die Leistung eines invaliden Elternteils. Der eigene Schutz des Kindes wird separat erfasst.";if(children)childBox.querySelector(".children-slot").appendChild(children);
    var childIds=["childTarget","childPrivate","childSaving","childYears"],storageKey="combinvest.pension.child-plan";
    try{var saved=JSON.parse(localStorage.getItem(storageKey)||"{}");childIds.forEach(function(id){if(saved[id]!=null)document.getElementById(id).value=saved[id];});}catch(_e){}
    function childRender(){var target=+document.getElementById("childTarget").value||0,privateValue=+document.getElementById("childPrivate").value||0,saving=+document.getElementById("childSaving").value||0,years=+document.getElementById("childYears").value||0;document.getElementById("childPrivateOut").textContent=money(privateValue);document.getElementById("childGapOut").textContent=money(Math.max(0,target-privateValue));document.getElementById("childCapitalOut").textContent=money(saving*12*years);var data={};childIds.forEach(function(id){data[id]=document.getElementById(id).value;});localStorage.setItem(storageKey,JSON.stringify(data));if(window.CombinvestCRM)CombinvestCRM.save("pension-child-plan",data);}
    childIds.forEach(function(id){document.getElementById(id).addEventListener("input",childRender);});childRender();

    var title=result.querySelector(".section-title"),caseLabel=document.getElementById("caseLabel"),period=el("div","period-switch",'<button type="button" data-period="year" class="active">Jahr</button><button type="button" data-period="month">Monat</button>');caseLabel.before(period);
    result.querySelector(".metrics").before(el("small","period-help","Leistungsfelder links bleiben Jahreswerte."));
    var currentPeriod="year",converting=false;
    function parseCHF(t){return Number(String(t||"").replace(/[^0-9-]/g,""))||0;}
    function convert(){if(converting)return;converting=true;["target","total","gap"].forEach(function(id){var n=document.getElementById(id);if(!n)return;var annual=Number(n.dataset.annual)||parseCHF(n.textContent);n.dataset.annual=annual;n.textContent=money(currentPeriod==="month"?annual/12:annual);var sm=n.previousElementSibling;if(sm)sm.textContent=sm.textContent.replace(/ \/ (Jahr|Monat)/," / "+(currentPeriod==="month"?"Monat":"Jahr"));});document.querySelectorAll("#details .detail-row b").forEach(function(n){if(n.textContent.indexOf("%")>-1)return;var annual=Number(n.dataset.annual)||parseCHF(n.textContent);n.dataset.annual=annual;n.textContent=money(currentPeriod==="month"?annual/12:annual);});document.querySelectorAll("#stack .segment").forEach(function(n){var annual=Number(n.dataset.annual)||parseCHF(n.title);n.dataset.annual=annual;n.dataset.tooltip=(n.title.split(":")[0]||"Leistung")+": "+money(currentPeriod==="month"?annual/12:annual)+" / "+(currentPeriod==="month"?"Monat":"Jahr");if(n.textContent)n.textContent=money(currentPeriod==="month"?annual/12:annual);});converting=false;}
    period.addEventListener("click",function(e){var b=e.target.closest("button");if(!b)return;currentPeriod=b.dataset.period;period.querySelectorAll("button").forEach(function(x){x.classList.toggle("active",x===b);});convert();});
    var observer=new MutationObserver(function(){if(converting)return;var needsMonthly=false;["target","total","gap"].forEach(function(id){var n=document.getElementById(id);if(!n)return;var shown=parseCHF(n.textContent),old=Number(n.dataset.annual)||0;if(currentPeriod==="year"){n.dataset.annual=shown;}else if(shown!==Math.round(old/12)){n.dataset.annual=shown;needsMonthly=true;}});document.querySelectorAll("#stack .segment").forEach(function(n){n.dataset.annual=parseCHF(n.title);});document.querySelectorAll("#details .detail-row b").forEach(function(n){if(n.textContent.indexOf("%")>-1)return;var shown=parseCHF(n.textContent),old=Number(n.dataset.annual)||0;if(currentPeriod==="year")n.dataset.annual=shown;else if(shown!==Math.round(old/12)){n.dataset.annual=shown;needsMonthly=true;}});decorateSources();if(currentPeriod==="month"&&needsMonthly)setTimeout(convert,0);});observer.observe(result,{childList:true,subtree:true,characterData:true});
    function decorateSources(){source.querySelectorAll(".money-row").forEach(function(row){var input=row.querySelector("input"),label=row.querySelector("label");if(!input||row.querySelector(".source-badge"))return;label.after(el("span","source-badge "+(input.disabled?"estimate":"exact"),input.disabled?"Richtwert":"Eingabe"));});}
    decorateSources();
    var tooltip=el("div","pension-tooltip","");document.body.appendChild(tooltip);document.getElementById("stack").addEventListener("mousemove",function(e){var s=e.target.closest(".segment");if(!s)return;tooltip.textContent=s.dataset.tooltip||s.title;tooltip.style.left=(e.clientX+14)+"px";tooltip.style.top=(e.clientY+14)+"px";tooltip.classList.add("show");});document.getElementById("stack").addEventListener("mouseleave",function(){tooltip.classList.remove("show");});
    document.querySelectorAll(".warning").forEach(function(n){n.remove();});
    var sources=el("details","pension-sources",'<summary>Berechnungsgrundlagen und Datenqualität</summary><div class="pension-sources-body">AHV/IV wird anhand Ihrer Angaben und der Rentenskala berechnet. BVG-Minimum ist ein Richtwert; Ausweiswerte, UVG-Leistungen und Policen gelten als exakte Eingaben. Koordination und Überentschädigung müssen mit den zuständigen Stellen geprüft werden. <a href="https://www.ahv-iv.ch/p/4.04.d" target="_blank" rel="noopener">AHV/IV-Leistungen</a> · <a href="https://www.ahv-iv.ch/de/Sozialversicherungen/Invalidenversicherung-IV/Invalidenrenten" target="_blank" rel="noopener">IV-Rentenanspruch</a> · <a href="https://www.bsv.admin.ch/de/invalidenvorsorge-beruflichen-vorsorge" target="_blank" rel="noopener">BVG-Invalidenvorsorge</a> · Stand 2026.</div>');document.querySelector("main").appendChild(sources);
    convert();
  }
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();
