(function(){
  "use strict";
  var GROUPS={
    household:{label:"Hausrat",items:[
      {id:"fire",label:"Feuer & Elementar",d:"Deckt Schäden am Hausrat durch Feuer und versicherte Naturereignisse.",a:"Zum Beispiel Brand, Blitzschlag, Sturm, Hagel oder Überschwemmung im vereinbarten Umfang.",w:"Versicherungssumme, Selbstbehalt und die genaue Definition von Elementarereignissen prüfen."},
      {id:"water",label:"Wasser",d:"Deckt bestimmte Wasserschäden an Ihrem Hausrat.",a:"Zum Beispiel Schäden durch Leitungswasser oder auslaufende Anlagen, je nach Vertrag.",w:"Grundwasser, Rückstau und Schäden am Gebäude sind nicht automatisch gleich gedeckt."},
      {id:"theft",label:"Einbruch & Beraubung",d:"Schützt bei versichertem Einbruchdiebstahl und Beraubung.",a:"Ersatz für gestohlene oder beschädigte Haushaltsgegenstände bis zu den vereinbarten Limiten.",w:"Wertsachenlimiten und Nachweispflichten besonders beachten."},
      {id:"awayTheft",label:"Einfacher Diebstahl auswärts",d:"Ergänzt den Schutz für Diebstahl ausserhalb des Zuhauses.",a:"Zum Beispiel bei Diebstahl von Gepäck oder persönlichen Gegenständen unterwegs.",w:"Verlust und unbeaufsichtigt zurückgelassene Sachen sind häufig eingeschränkt."},
      {id:"glass",label:"Glasbruch",d:"Deckt ausgewählte Bruchschäden an Mobiliar- oder Gebäudeglas.",a:"Je nach Variante etwa Tischplatten, Lavabos, Fenster oder Kochfelder.",w:"Mobiliar- und Gebäudeglas sind getrennte Bausteine; bei Miete Zuständigkeit prüfen."},
      {id:"valuables",label:"Wertsachen",d:"Erweitert den Schutz für besonders wertvolle Gegenstände.",a:"Zum Beispiel Schmuck, Uhren, Kunst oder Musikinstrumente mit vereinbarter Summe.",w:"Einzelwerte, Verzeichnisse, Belege und Aufbewahrungsvorschriften dokumentieren."},
      {id:"cyber",label:"Cyber",d:"Bietet je nach Produkt Hilfe bei bestimmten privaten Cyberereignissen.",a:"Mögliche Leistungen sind Datenrettung, Unterstützung bei Onlinebetrug oder Identitätsmissbrauch.",w:"Deckungstatbestände und Limiten unterscheiden sich stark je Produkt."}
    ]},
    liability:{label:"Privathaftpflicht",items:[
      {id:"tenant",label:"Mieterschäden",d:"Deckt versicherte Schäden an gemieteten Räumen.",a:"Zum Beispiel unbeabsichtigte Schäden an Wohnungsteilen, für die Sie haftbar sind.",w:"Abnutzung, allmähliche Schäden und Selbstbehalte prüfen."},
      {id:"borrowed",label:"Geliehene Sachen",d:"Ergänzt die Haftpflicht für bestimmte geliehene Gegenstände.",a:"Schäden an vorübergehend übernommenen Sachen können je nach Vertrag gedeckt sein.",w:"Fahrzeuge, beruflich genutzte Sachen und Obhutsschäden sind oft eingeschränkt."},
      {id:"grossNegligence",label:"Grobfahrlässigkeit",d:"Kann den Schutz vor Leistungskürzungen bei grobfahrlässig verursachten Schäden erweitern.",a:"Der Versicherer verzichtet im vereinbarten Umfang auf eine Kürzung oder einen Rückgriff.",w:"Absicht und bestimmte schwere Pflichtverletzungen bleiben ausgeschlossen."},
      {id:"animals",label:"Tierhalter",d:"Erfasst Haftpflichtrisiken durch gehaltene Tiere.",a:"Schäden an Dritten durch Haustiere können im vereinbarten Rahmen gedeckt sein.",w:"Tierart, kantonale Vorgaben und ausgeschlossene Tiere prüfen."}
    ]},
    motor:{label:"Motorfahrzeug",items:[
      {id:"liability",label:"Motorfahrzeug-Haftpflicht",fixed:true,d:"Gesetzlich erforderliche Grunddeckung für zugelassene Motorfahrzeuge.",a:"Deckt berechtigte Schadenersatzansprüche Dritter aus dem Betrieb des Fahrzeugs.",w:"Eigene Fahrzeugschäden sind damit nicht gedeckt."},
      {id:"partial",label:"Teilkasko",d:"Schützt das eigene Fahrzeug bei ausgewählten Ereignissen ohne Kollision.",a:"Typisch sind Diebstahl, Feuer, Elementar, Glas, Tierkollision oder Marder – je nach Produkt.",w:"Leistungsumfang, Zeitwertregel und Selbstbehalte vergleichen."},
      {id:"collision",label:"Kollisionskasko / Vollkasko",d:"Ergänzt die Teilkasko um selbst verursachte Kollisionsschäden am eigenen Fahrzeug.",a:"Reparatur oder Entschädigung des eigenen Fahrzeugs nach versicherter Kollision.",w:"Zeitwertzusatz, Selbstbehalt, Bonusfolgen und Leasingvorgaben prüfen."},
      {id:"parking",label:"Parkschaden",d:"Deckt bestimmte Schäden am parkierten Fahrzeug durch unbekannte Dritte.",a:"Zum Beispiel Dellen oder Kratzer, sofern Ereignis und Umfang versichert sind.",w:"Anzahl Fälle, Schadenhöhe und Fahrzeugwertlimiten beachten."},
      {id:"grossNegligence",label:"Grobfahrlässigkeitsschutz",d:"Kann Rückgriffe oder Kürzungen nach grobfahrlässigem Verhalten reduzieren.",a:"Der Versicherer verzichtet im vereinbarten Rahmen auf Rückgriff oder Leistungskürzung.",w:"Alkohol, Drogen, Raserdelikte und weitere schwere Verstösse bleiben regelmässig ausgeschlossen."},
      {id:"assistance",label:"Pannenhilfe & Assistance",d:"Organisiert Hilfe bei Panne oder Unfall.",a:"Je nach Vertrag Abschleppen, Weiterreise, Ersatzfahrzeug oder Rücktransport.",w:"Geltungsgebiet und bereits vorhandene Deckung über Hersteller, Club oder Kreditkarte prüfen."},
      {id:"occupants",label:"Insassenunfall",d:"Ergänzt Leistungen für Fahrer und Mitfahrende nach einem Unfall.",a:"Kapital-, Heilungs- oder Taggeldleistungen gemäss Vertrag.",w:"Mögliche Doppelversicherung mit UVG und Krankenversicherung prüfen."}
    ]}
  };
  var GENERAL={
    household:{label:"Hausratversicherung",category:"Haushalt",d:"Versichert den beweglichen Hausrat gegen vereinbarte Gefahren.",a:"Ihre persönlichen Sachen zu Hause und teilweise unterwegs.",w:"Die Versicherungssumme sollte zum tatsächlichen Wiederbeschaffungswert passen."},
    liability:{label:"Privathaftpflicht",category:"Haftpflicht",d:"Schützt vor berechtigten Schadenersatzforderungen Dritter.",a:"Personen- und Sachschäden aus dem privaten Alltag im vereinbarten Umfang.",w:"Haushaltsform, Deckungssumme und Ausschlüsse müssen zur Situation passen."},
    motor:{label:"Motorfahrzeugversicherung",category:"Fahrzeug",d:"Kombiniert die obligatorische Haftpflicht mit frei wählbaren Fahrzeugdeckungen.",a:"Haftpflicht gegenüber Dritten sowie optional Schäden am eigenen Fahrzeug.",w:"Fahrzeugwert, Alter, Nutzung und Leasing beeinflussen den passenden Umfang."}
  };
  var dialog=document.getElementById("infoDialog");
  function byId(id){return document.getElementById(id);}
  function makeGrid(group){byId(group+"Grid").innerHTML=GROUPS[group].items.map(function(x){return '<div class="coverage-item '+(x.fixed?'is-fixed':'')+'"><div class="coverage-label"><span>'+x.label+'</span><button class="info-button" type="button" data-info="'+group+':'+x.id+'" aria-label="Erklärung zu '+x.label+'">i</button></div><label class="existing-check"><input type="checkbox" data-existing-group="'+group+'" data-existing="'+x.id+'"><span>Bestehend</span></label><label class="switch"><input type="checkbox" data-group="'+group+'" data-coverage="'+x.id+'" '+(x.fixed?'checked disabled':'')+'><span aria-hidden="true"></span><em>Gewünscht</em></label></div>';}).join("");}
  Object.keys(GROUPS).forEach(makeGrid);
  function enabled(group){return byId(group+"Enabled").checked;}
  function selected(group){if(!enabled(group))return[];return GROUPS[group].items.filter(function(x){var el=document.querySelector('[data-group="'+group+'"][data-coverage="'+x.id+'"]');return el&&el.checked;}).map(function(x){return{id:x.id,label:x.label};});}
  function existingSelected(group){if(!byId(group+"Existing").checked)return[];return GROUPS[group].items.filter(function(x){var el=document.querySelector('[data-existing-group="'+group+'"][data-existing="'+x.id+'"]');return el&&el.checked;}).map(function(x){return{id:x.id,label:x.label};});}
  function payload(){var existing=[].concat(existingSelected("household"),existingSelected("liability"),existingSelected("motor"));return{version:2,household:{enabled:enabled("household"),existing:byId("householdExisting").checked,residence:byId("residence").value,householdSize:Number(byId("householdSize").value)||1,householdValue:Number(byId("householdValue").value)||0,covers:selected("household"),existingCovers:existingSelected("household")},liability:{enabled:enabled("liability"),existing:byId("liabilityExisting").checked,covers:selected("liability"),existingCovers:existingSelected("liability")},motor:{enabled:enabled("motor"),existing:byId("motorExisting").checked,vehicleYear:Number(byId("vehicleYear").value)||null,vehicleValue:Number(byId("vehicleValue").value)||0,leasing:byId("leasing").checked,covers:selected("motor"),existingCovers:existingSelected("motor")},notes:byId("insuranceNotes").value.trim(),selected:[].concat(selected("household"),selected("liability"),selected("motor")).map(function(x){return x.label;}),existingSelected:existing.map(function(x){return x.label;}),updatedAt:new Date().toISOString()};}
  function saveDraft(){if(window.CombinvestCRM)CombinvestCRM.save("insurance-needs-draft",payload());}
  function render(){Object.keys(GROUPS).forEach(function(group){var on=enabled(group);byId(group+"Options").hidden=!on;var main=byId(group+"Enabled");main.closest(".switch").querySelector("em").textContent=on?"Gewünscht":"Aus";document.querySelectorAll('[data-group="'+group+'"]:not(:disabled)').forEach(function(el){el.closest(".switch").querySelector("em").textContent=el.checked?"Gewünscht":"Aus";});});var groups=Object.keys(GROUPS).map(function(key){return{key:key,label:GROUPS[key].label,items:selected(key)};}).filter(function(g){return g.items.length;}),wanted=[].concat(selected("household"),selected("liability"),selected("motor")).map(function(x){return x.label;}),existing=[].concat(existingSelected("household"),existingSelected("liability"),existingSelected("motor")).map(function(x){return x.label;}),gaps=wanted.filter(function(x){return existing.indexOf(x)<0;});var count=wanted.length;byId("selectedCount").textContent=count;byId("gapCount").textContent=gaps.length;byId("summaryEmpty").hidden=count>0;byId("summaryGroups").innerHTML=groups.map(function(g){return '<section class="summary-group"><h3>'+g.label+'</h3><ul>'+g.items.map(function(x){return'<li>'+x.label+'</li>';}).join("")+'</ul></section>';}).join("");var hint=byId("checkHint");if(enabled("motor")){var year=Number(byId("vehicleYear").value),leasing=byId("leasing").checked,collision=selected("motor").some(function(x){return x.id==="collision";});hint.hidden=false;hint.innerHTML='<strong>Prüfhinweis</strong><p>'+((leasing||year&&new Date().getFullYear()-year<=5)&&!collision?'Bei einem geleasten oder neueren Fahrzeug sollte eine Kollisionskasko geprüft werden.':'Deckungsumfang und Selbstbehalte mit der bestehenden Police vergleichen.')+'</p>';}else hint.hidden=true;saveDraft();}
  function showInfo(key){var parts=key.split(":"),x=parts.length===1?GENERAL[key]:GROUPS[parts[0]].items.find(function(item){return item.id===parts[1];});if(!x)return;byId("infoCategory").textContent=x.category||GROUPS[parts[0]].label;byId("infoTitle").textContent=x.label;byId("infoDescription").textContent=x.d;byId("infoAdds").textContent=x.a;byId("infoWatch").textContent=x.w;dialog.showModal();}
  function restore(){var data=window.CombinvestCRM&&(CombinvestCRM.data("insurance-needs-draft",null)||CombinvestCRM.data("insurance-needs",null));if(!data)return;["household","liability","motor"].forEach(function(group){var d=data[group]||{};byId(group+"Enabled").checked=!!d.enabled;byId(group+"Existing").checked=!!d.existing;(d.covers||[]).forEach(function(item){var id=typeof item==="string"?item:item.id,el=document.querySelector('[data-group="'+group+'"][data-coverage="'+id+'"]');if(el)el.checked=true;});(d.existingCovers||[]).forEach(function(item){var id=typeof item==="string"?item:item.id,el=document.querySelector('[data-existing-group="'+group+'"][data-existing="'+id+'"]');if(el)el.checked=true;});});var h=data.household||{},m=data.motor||{};byId("residence").value=h.residence||"tenant";byId("householdSize").value=h.householdSize||1;byId("householdValue").value=h.householdValue||"";byId("vehicleYear").value=m.vehicleYear||"";byId("vehicleValue").value=m.vehicleValue||"";byId("leasing").checked=!!m.leasing;byId("insuranceNotes").value=data.notes||"";}
  document.addEventListener("click",function(event){var button=event.target.closest("[data-info]");if(button)showInfo(button.dataset.info);});
  byId("closeInfo").addEventListener("click",function(){dialog.close();});dialog.addEventListener("click",function(event){if(event.target===dialog)dialog.close();});
  byId("insuranceForm").addEventListener("change",render);byId("insuranceForm").addEventListener("input",function(){render();});
  byId("saveInsurance").addEventListener("click",function(){var ok=window.CombinvestCRM?CombinvestCRM.save("insurance-needs",payload()):false;byId("saveStatus").textContent=ok?"Auswahl wurde in die Analyse übernommen.":"Speichern nicht möglich.";});
  function syncExistingVisibility(){Object.keys(GROUPS).forEach(function(group){if(byId(group+"Existing").checked)byId(group+"Options").hidden=false;});}
  byId("insuranceForm").addEventListener("change",syncExistingVisibility);
  restore();render();syncExistingVisibility();
})();
