(function(){
  "use strict";
  var COVERAGES=[
    {id:"alternative",label:"Alternativmedizin",d:"Ergänzt ausgewählte komplementärmedizinische Behandlungen ausserhalb oder über die Leistungen der Grundversicherung hinaus.",a:"Je nach Produkt beispielsweise zusätzliche Beiträge an anerkannte Therapeutinnen, Therapeuten oder Methoden.",w:"Anerkennungslisten, Methoden, Jahreslimiten und Kostenanteile unterscheiden sich stark."},
    {id:"dental",label:"Zahnbehandlungen",d:"Ordentliche Zahnbehandlungen sind in der Grundversicherung grundsätzlich nicht enthalten.",a:"Je nach Produkt Beiträge an Kontrollen, Dentalhygiene, Füllungen oder weitere Zahnbehandlungen.",w:"Häufig gelten Gesundheitsprüfung, Karenzfrist, jährliche Limiten und prozentuale Kostenbeteiligung."},
    {id:"abroad",label:"Notfälle im Ausland",d:"Schliesst mögliche Kostenlücken bei medizinischen Notfällen auf Reisen, besonders ausserhalb EU/EFTA/UK.",a:"Je nach Produkt höhere Behandlungslimiten, Transport, Rückführung oder Assistance-Leistungen.",w:"Reisedauer, Länder, maximale Leistung und Ausschlüsse vor Abschluss prüfen."},
    {id:"orthodontics",label:"Zahnstellungskorrektur",d:"Ergänzt Kosten für kieferorthopädische Behandlungen, die von der Grundversicherung meist nicht übernommen werden.",a:"Je nach Produkt Beiträge an Spangen, Kontrollen und kieferorthopädische Behandlung.",w:"Eintrittsalter, Befund bei Abschluss, Wartefrist, Prozentanteil und Gesamtlimit sind entscheidend."},
    {id:"medication",label:"Nichtpflichtmedikamente",d:"Ergänzt Medikamente, die nicht oder nur eingeschränkt über die Grundversicherung vergütet werden.",a:"Je nach Produkt Beiträge an ärztlich verordnete Präparate ausserhalb der Pflichtlisten.",w:"Nur anerkannte Präparate und Indikationen; Selbstbehalt und Limiten beachten."},
    {id:"vision",label:"Brille und Kontaktlinsen",d:"Ergänzt die begrenzten gesetzlichen Leistungen für Sehhilfen.",a:"Periodischer Beitrag an Brillengläser, Fassungen oder Kontaktlinsen.",w:"Leistungsperiode, Maximalbetrag und anerkannte Anbieter vergleichen."},
    {id:"psychotherapy",label:"Psychotherapie",d:"Ergänzt Behandlungen, die nicht unter den Voraussetzungen der Grundversicherung abgerechnet werden können.",a:"Je nach Produkt Beiträge an zusätzliche Sitzungen oder anerkannte therapeutische Angebote.",w:"Ärztliche Anordnung, Anerkennung der Fachperson, Sitzungszahl und Jahreslimit prüfen."},
    {id:"rescue",label:"Suche, Rettung und Transport",d:"Ergänzt die begrenzte Beteiligung der Grundversicherung an medizinisch notwendigen Transport- und Rettungskosten.",a:"Je nach Produkt höhere Beiträge an Ambulanz, Rettung, Suche oder Bergung im In- und Ausland.",w:"Suche und Rettung werden oft unterschiedlich behandelt; Jahres- und Ereignislimiten prüfen."},
    {id:"prevention",label:"Prävention und Check-ups",d:"Ergänzt Vorsorgeuntersuchungen, Impfungen oder Check-ups ausserhalb der gesetzlichen Pflichtleistungen.",a:"Je nach Produkt Beiträge an definierte Vorsorgeprogramme und Untersuchungen.",w:"Leistungskatalog, Altersgrenzen, Intervalle und vorgängige Kostengutsprache beachten."},
    {id:"fitness",label:"Fitness und Gesundheitsförderung",d:"Unterstützt gesundheitsfördernde Aktivitäten, die nicht zur Grundversicherung gehören.",a:"Je nach Produkt Beiträge an anerkannte Fitnesscenter, Kurse oder Gesundheitsprogramme.",w:"Anbieterliste, Mindestabodauer, Nachweis und jährliches Beitragsmaximum prüfen."}
  ];
  var HOSPITAL={id:"hospital",label:"Spitalzusatzversicherung",d:"Ergänzt bei stationären Behandlungen Komfort und Wahlmöglichkeiten über den Standard der allgemeinen Abteilung hinaus.",a:"Je nach Stufe freie oder erweiterte Arztwahl, Ein- oder Zweibettzimmer sowie Abdeckung bestimmter Mehrkosten bei der Spitalwahl.",w:"Spitalliste, Vertragskliniken, Kostenbeteiligung bei Flex-Modellen, Gesundheitsprüfung und Ausschlüsse prüfen."};
  var grid=document.getElementById("coverageGrid"), dialog=document.getElementById("infoDialog");
  grid.innerHTML=COVERAGES.map(function(x){return '<div class="coverage-item"><div class="coverage-label"><span>'+x.label+'</span><button class="info-button" type="button" data-info="'+x.id+'" aria-label="Erklärung zu '+x.label+'">i</button></div><label class="existing-check"><input type="checkbox" data-existing="'+x.id+'"><span>Bestehend</span></label><label class="switch"><input type="checkbox" data-coverage="'+x.id+'"><span aria-hidden="true"></span><em>Gewünscht</em></label></div>';}).join("");
  function info(id){var x=id==="hospital"?HOSPITAL:COVERAGES.find(function(item){return item.id===id;});if(!x)return;document.getElementById("infoCategory").textContent=id==="hospital"?"Stationäre Ergänzung":"Ambulante Ergänzung";document.getElementById("infoTitle").textContent=x.label;document.getElementById("infoDescription").textContent=x.d;document.getElementById("infoAdds").textContent=x.a;document.getElementById("infoWatch").textContent=x.w;dialog.showModal();}
  function selection(){var items=[];var hospital=document.getElementById("hospitalEnabled").checked,level=document.querySelector('[name="hospitalLevel"]:checked');if(hospital)items.push("Spitalzusatz"+(level?" · "+({flex:"Flex",semi:"Halbprivat",private:"Privat"}[level.value]):""));document.querySelectorAll("[data-coverage]:checked").forEach(function(el){var x=COVERAGES.find(function(item){return item.id===el.dataset.coverage;});if(x)items.push(x.label);});return items;}
  function existingSelection(){var items=[];if(document.getElementById("hospitalExisting").checked)items.push("Spitalzusatz");document.querySelectorAll("[data-existing]:checked").forEach(function(el){var x=COVERAGES.find(function(item){return item.id===el.dataset.existing;});if(x)items.push(x.label);});return items;}
  function render(){var hospital=document.getElementById("hospitalEnabled"),options=document.getElementById("hospitalOptions");options.hidden=!hospital.checked;hospital.closest(".switch").querySelector("em").textContent=hospital.checked?"Gewünscht":"Aus";document.querySelectorAll("[data-coverage]").forEach(function(el){el.closest(".switch").querySelector("em").textContent=el.checked?"Gewünscht":"Aus";});var items=selection(),existing=existingSelection(),gaps=items.filter(function(item){return existing.indexOf(item.split(" · ")[0])<0;});document.getElementById("selectedCount").textContent=items.length;document.getElementById("gapCount").textContent=gaps.length;document.getElementById("summaryEmpty").hidden=items.length>0;document.getElementById("summaryList").innerHTML=items.map(function(item){return "<li>"+item+"</li>";}).join("");saveDraft();}
  function payload(){var level=document.querySelector('[name="hospitalLevel"]:checked');return{hospital:document.getElementById("hospitalEnabled").checked,existingHospital:document.getElementById("hospitalExisting").checked,hospitalLevel:level?level.value:null,ambulatory:COVERAGES.reduce(function(out,x){out[x.id]=document.querySelector('[data-coverage="'+x.id+'"]').checked;return out;},{}),existingAmbulatory:COVERAGES.reduce(function(out,x){out[x.id]=document.querySelector('[data-existing="'+x.id+'"]').checked;return out;},{}),notes:document.getElementById("coverageNotes").value,selected:selection(),existingSelected:existingSelection(),updatedAt:new Date().toISOString()};}
  function saveDraft(){if(window.CombinvestCRM)CombinvestCRM.save("supplementaryInsuranceDraft",payload());}
  function restore(){var data=window.CombinvestCRM&&CombinvestCRM.data("supplementaryInsuranceDraft",null)||window.CombinvestCRM&&CombinvestCRM.data("supplementaryInsurance",null);if(!data)return;document.getElementById("hospitalEnabled").checked=!!data.hospital;document.getElementById("hospitalExisting").checked=!!data.existingHospital;if(data.hospitalLevel){var radio=document.querySelector('[name="hospitalLevel"][value="'+data.hospitalLevel+'"]');if(radio)radio.checked=true;}Object.keys(data.ambulatory||{}).forEach(function(id){var input=document.querySelector('[data-coverage="'+id+'"]');if(input)input.checked=!!data.ambulatory[id];});Object.keys(data.existingAmbulatory||{}).forEach(function(id){var input=document.querySelector('[data-existing="'+id+'"]');if(input)input.checked=!!data.existingAmbulatory[id];});document.getElementById("coverageNotes").value=data.notes||"";}
  document.addEventListener("click",function(event){var button=event.target.closest("[data-info]");if(button)info(button.dataset.info);});
  document.getElementById("closeInfo").addEventListener("click",function(){dialog.close();});dialog.addEventListener("click",function(event){if(event.target===dialog)dialog.close();});
  document.getElementById("coverageForm").addEventListener("change",render);document.getElementById("coverageNotes").addEventListener("input",saveDraft);
  document.getElementById("saveCoverage").addEventListener("click",function(){var ok=window.CombinvestCRM?CombinvestCRM.save("supplementaryInsurance",payload()):false;document.getElementById("saveStatus").textContent=ok?"In die Analyse übernommen.":"Speichern nicht möglich.";});
  function syncExistingVisibility(){if(document.getElementById("hospitalExisting").checked)document.getElementById("hospitalOptions").hidden=false;}
  document.getElementById("coverageForm").addEventListener("change",syncExistingVisibility);
  restore();render();syncExistingVisibility();
})();
